package ac.iiti.gkalyan0510.fastedge;

import java.util.Arrays;
import java.util.List;

public class Constants {
    public static final String ACITON_EXTRA_OPEN_PANEL = "open_panel";
    public static final String ACITON_EXTRA_PANEL_ACTIVE_AREA_CHANGED = "panel_active_area_changed";
    public static final String ACTION_CREATE_ITEM = "com.samsung.androd.app.appsedge.action.CREATE_ITEM";
    public static final String ACTION_EXTRA_APPS_KEY = "action_apps_key";
    public static final String ACTION_EXTRA_APPS_PANEL_UPDATE = "com.samsung.android.app.appsedge.action.panel.update";
    public static final String ACTION_EXTRA_HELP_TEXT_UPDATE = "com.samsung.android.app.appsedge.action.panel.update.HELP";
    public static final String ACTION_PACKAGE_CHANGED = "com.samsung.androd.app.appsedge.action.PACKAGE_CHANGED";
    public static final String ACTION_REMOVE_ITEM = "com.samsung.androd.app.appsedge.action.REMOVE_ITEM";
    public static final String ACTION_UPDATE_HELP_TEXT = "update_help_text";
    public static final String ACTION_UPDATE_ITEM = "com.samsung.androd.app.appsedge.action.UPDATE_ITEM";
    public static final String ACTIVE_EDGE_AREA = "active_edge_area";
    public static final int ACTIVE_RIGHT_AREA = 1;
    public static final String APPS_EDGE_CLS_NAME = "com.samsung.android.app.appsedge.edgepanel.AppsEdgePanelProvider";
    public static final String APPS_EDGE_PKG_NAME = "com.samsung.android.app.appsedge";
    public static final String BROWSER_PACKAGE = "com.sec.android.app.sbrowser";
    public static final String CALCULATOR_PACKAGE = "com.sec.android.app.popupcalculator";
    public static final String CALENDAR_PACKAGE_NAME = "com.android.calendar";
    public static final String CAMERA_PACKAGE = "com.sec.android.app.camera";
    public static final String CLOCK_PACKAGE_NAME = "com.sec.android.app.clockpackage";
    public static final String CLOCK_PACKAGE_NAME_CHN = "com.sec.android.app.clockpackagechina";
    public static final String CONTACT_PACKAGE_NAME = "com.android.contacts";
    public static final String CONTACT_PACKAGE_NAME_DCM = "com.samsung.contacts";
    public static final int DEFAULT_COLMUN_COUNT = 2;
    public static List<String> DEFAULT_FREQUELTLY_APP_LIST = Arrays.asList(new String[]{"com.facebook.katana", CALCULATOR_PACKAGE, "com.instagram.android", "com.google.android.youtube", CLOCK_PACKAGE_NAME, "com.sec.android.app.music", "com.facebook.orca", "com.sec.android.gallery3d"});
    public static final int EXECUTABLEINFO_ACTIVITY = 0;
    public static final int EXECUTABLEINFO_BROADCAST = 2;
    public static final int EXECUTABLEINFO_SERVICE = 1;
    public static final String LOCK_SCREEN_SHOW_NOTIFICATIONS = "lock_screen_show_notifications";
    public static final String MESSAGE_PACKAGE_NAME = "com.android.mms";
    public static final int MINIMUM_USAGE_COUNT = 5;
    public static final String NEW_CALENDAR_PACKAGE_NAME = "com.samsung.android.calendar";
    public static final String NEW_CONTACT_PACKAGE_NAME = "com.samsung.android.contacts";
    public static final String NEW_MESSAGE_PACKAGE_NAME = "com.samsung.android.messaging";
    public static final String NEW_QUICK_CONNECT_ID = "executable://com.samsung.android.oneconnect/1394050157";
    public static final String NEW_QUICK_CONNECT_PACKAGE = "com.samsung.android.oneconnect";
    public static final String PRESET_DEFAULT_APP_LIST = "0,com.sec.android.app.popupcalculator;1,com.sec.android.app.clockpackage;2,com.google.android.youtube;3,com.android.chrome;5,com.sec.android.gallery3d;6,com.android.settings;6,com.samsung.android.calendar;7,com.google.android.apps.maps;8,com.google.android.apps.tachyon;";
    public static final String PRESET_FOLDER = "preset_folder";
    public static final String QUICK_CONNECT_ID = "executable://com.samsung.android.qconnect/2256488206";
    public static final String QUICK_CONNECT_PACKAGE = "com.samsung.android.qconnect";
    public static final String REQUEST_BACKUP_APPS_EDGE = "com.samsung.android.intent.action.REQUEST_BACKUP_EDGESCREEN_APPSEDGE_SETTING";
    public static final String REQUEST_RESTORE_APPS_EDGE = "com.samsung.android.intent.action.REQUEST_RESTORE_EDGESCREEN_APPSEDGE_SETTING";
    public static final String RESPONSE_BACKUP_APPS_EDGE = "com.samsung.android.intent.action.RESPONSE_BACKUP_EDGESCREEN_APPSEDGE_SETTING";
    public static final String RESPONSE_RESTORE_APPS_EDGE = "com.samsung.android.intent.action.RESPONSE_RESTORE_EDGESCREEN_APPSEDGE_SETTING";
    public static final String SAMSUNG_APPS_CLASS_NAME = "com.sec.android.app.samsungapps.Main";
    public static final String SAMSUNG_APPS_PACKAGE_NAME = "com.sec.android.app.samsungapps";
    public static final String SECURE_FOLDER_PACKAGE_NAME = "com.sec.knox.switcher";
    public static final int SETTINGS_APP_COLUMN_NUMBER = 5;
    public static final int SETTINGS_FREQUENTLY_USED_LIST_COUNT_1COLUMN = 4;
    public static final int SETTINGS_FREQUENTLY_USED_LIST_COUNT_2COLUMN = 3;
    public static final String SETTINGS_TASK_EMPTY = "empty";
    public static final String SHARED_PREF = "pref";
    public static final String STK2_PACKAGE = "com.android.stk2";
    public static final String STK_PACKAGE = "com.android.stk";
    public static final String TAG_CSCFEATURE_CLOCK_CONFIGREPLACEPACKAGE = "CscFeature_Clock_ConfigReplacePackage";
    public static final String TAG_CSCFEATURE_CONTACT_REPLACEPACKAGEAS = "CscFeature_Contact_ReplacePackageAs";
    public static final String UPDATE_TIME = "update_time";
    public static final String UPDATE_TIME_PANEL = "update_time_panel";
}
